[package]
name = "smelly-connect"
version = "0.6.1"
edition = "2024"

[dependencies]
rsa = "0.9"
smelly-tls = { path = "../smelly-tls", features = ["tokio"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "io-util", "net"] }
hex = "0.4"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "form"] }
roxmltree = "0.21"
smoltcp = { version = "0.13", default-features = false, features = ["std", "async", "medium-ip", "proto-ipv4", "proto-ipv4-fragmentation", "socket-tcp", "socket-icmp", "socket-udp"] }
tracing = "0.1"

[dev-dependencies]
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
tokio-rustls = "0.26"
trybuild = "1"
